global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'telemetry'
    replica: '0'

scrape_configs:
  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/node-exporters.yaml'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [host]
        target_label: hostname

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus'
          role: 'monitoring'

