apiVersion: 1

datasources:
  - name: Backtest Dev
    uid: influxdb-algo-trader-backtest-dev
    type: influxdb
    access: proxy
    url: http://influxdb:8181
    database: backtest-dev
    jsonData:
      version: SQL
      dbName: backtest-dev
      httpMode: POST
      insecureGrpc: true
      tlsSkipVerify: true
    secureJsonData:
      token: $INFLUXDB3_AUTH_TOKEN
    editable: false
