apiVersion: 1

datasources:
  - name: Backtest
    uid: influxdb-algo-trader-backtest
    type: influxdb
    access: proxy
    url: http://influxdb:8181
    database: backtest
    jsonData:
      version: SQL
      dbName: backtest
      httpMode: POST
      insecureGrpc: true
      tlsSkipVerify: true
    secureJsonData:
      token: $INFLUXDB3_AUTH_TOKEN
    editable: false
