apiVersion: 1

datasources:
  - name: OHLCV
    uid: influxdb-algo-trader-ohlcv
    type: influxdb
    access: proxy
    url: http://influxdb:8181
    database: algo-trader-ohlcv
    jsonData:
      version: SQL
      dbName: algo-trader-ohlcv
      httpMode: POST
      insecureGrpc: true
      tlsSkipVerify: true
    secureJsonData:
      token: $INFLUXDB3_AUTH_TOKEN
    isDefault: true
    editable: true
