services:
  redis:
    image: artificer-redis:latest
    container_name: population-redis
    ports:
      - "127.0.0.1:6379:6379"  # Should probably make this a variable
    networks:
      - population-network
    restart: unless-stopped

networks:
  population-network:
    driver: bridge